### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by djays1618** [jokernotgod/Pornhub#15]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "crawler.py", line 66, in download
    urllib.request.urlretrieve(url, '%s' % (filepath))
AttributeError: 'module' object has no attribute 'request'
2018-08-22T03:30:18Z <Greenlet "Greenlet-103" at 0x7f1d5127edb8: download('https://cv.phncdn.com/videos/201602/09/68280191/1, 'ph5accc35094e31', 'webm')> failed with AttributeError

23:30:18,791947 crawler-ln:

**Comment by jokernotgod** [comment]
https://github.com/jokernotgod/Pornhub/issues/1
